[phases.setup]
nixPkgs = ['php82', 'php82Extensions.gd', 'php82Extensions.mbstring', 'php82Extensions.xml', 'php82Extensions.curl', 'nodejs']

[phases.build]
# Di sini hanya untuk install library, jangan ada perintah artisan dulu
cmds = ['composer install --no-dev', 'npm install', 'npm run build']

[phases.start]
# Di sini baru kita jalankan perintah Laravel karena folder vendor sudah siap
cmds = [
    'php artisan migrate --force',
    'php artisan storage:link',
    'apache2-foreground'
]