[phases.setup]
nixPkgs = ['php82', 'php82Extensions.gd', 'php82Extensions.mbstring', 'php82Extensions.xml', 'php82Extensions.curl', 'nodejs_20']

[phases.install]
cmds = [
    'curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer',
    'composer install --no-dev --ignore-platform-reqs'
]

[phases.build]
cmds = [
    'npm install',
    'npm run build'
]

[start]
cmd = 'php artisan migrate --force && php artisan storage:link && apache2-foreground'